@ stdcall GetApplicationUserModelId(ptr ptr ptr)
@ stdcall GetCurrentApplicationUserModelId(ptr ptr)
@ stdcall GetCurrentPackageFamilyName(ptr ptr)
@ stdcall GetCurrentPackageFullName(ptr ptr)
@ stdcall GetCurrentPackageId(ptr ptr)
@ stdcall GetCurrentPackagePath(ptr ptr)
@ stdcall GetPackageFamilyName(ptr ptr ptr)
@ stdcall GetPackageFullName(ptr ptr ptr)
@ stdcall GetPackageId(ptr ptr ptr)
@ stdcall IsAppContainerProcess(ptr)
@ stdcall PackageFamilyNameFromFullName(wstr ptr ptr)
@ stdcall PackageFullNameFromId(ptr ptr ptr)
@ stdcall PackageIdFromFullName(wstr long ptr ptr)

@ stdcall D3D11CreateDevice(ptr long ptr long ptr long long ptr ptr ptr)
@ stdcall D3D11CreateDeviceAndSwapChain(ptr long ptr long ptr long long ptr ptr ptr ptr ptr)
@ stdcall CreateDXGIFactory(ptr ptr)
@ stdcall CreateDXGIFactory1(ptr ptr)
@ stdcall CreateDXGIFactory2(long ptr ptr)
@ stdcall D2D1CreateFactory(long ptr ptr ptr)
@ stdcall DWriteCreateFactory(long ptr ptr)

@ stdcall SetProcessMitigationPolicy(long ptr long)
@ stdcall GetProcessMitigationPolicy(ptr long ptr long)
@ stdcall GetProcessPreferredUILanguages(long ptr ptr ptr)
@ stdcall GetTickCount64()
@ stdcall SetProcessDEPPolicy(long)
@ stdcall GetSystemTimePreciseAsFileTime(ptr)
@ stdcall NtSetInformationProcess(ptr long ptr long)
@ stdcall SetThreadInformation(ptr long ptr long)
@ stdcall GetThreadInformation(ptr long ptr long)
