@ stdcall GetApplicationUserModelId(ptr ptr ptr)
@ stdcall GetCurrentApplicationUserModelId(ptr ptr)
@ stdcall GetCurrentPackageFamilyName(ptr ptr)
@ stdcall GetCurrentPackageFullName(ptr ptr)
@ stdcall GetCurrentPackageId(ptr ptr)
@ stdcall GetCurrentPackagePath(ptr ptr)
@ stdcall GetPackageFamilyName(ptr ptr ptr)
@ stdcall GetPackageFullName(ptr ptr ptr)
@ stdcall GetPackageId(ptr ptr ptr)
@ stdcall IsAppContainerProcess(ptr)
@ stdcall PackageFamilyNameFromFullName(wstr ptr ptr)
@ stdcall PackageFullNameFromId(ptr ptr ptr)
@ stdcall PackageIdFromFullName(wstr long ptr ptr)
