@ stdcall IsWindows10OrGreater()
@ stdcall IsWindows7OrGreater()
@ stdcall IsWindows7SP1OrGreater()
@ stdcall IsWindows8OrGreater()
@ stdcall IsWindows8Point1OrGreater()
@ stdcall IsWindowsServer()
@ stdcall IsWindowsVersionOrGreater(long long long)
@ stdcall IsWindowsVistaOrGreater()
@ stdcall IsWindowsVistaSP1OrGreater()
@ stdcall IsWindowsVistaSP2OrGreater()
@ stdcall IsWindowsXPOrGreater()
@ stdcall IsWindowsXPSP1OrGreater()
@ stdcall IsWindowsXPSP2OrGreater()
@ stdcall IsWindowsXPSP3OrGreater()
